axis_linear_x: 3
axis_linear_y: 0
axis_angular: 2

speed_up: 3        # Speed increased by 20%
speed_down: 1      # Speed decreased by 20%
deadman: 4
operating_mode: 5  # differential drive mode and mecanum drive mode (Not used now)

max_linear_x: 1.5
max_linear_y: 0
max_angular: 3.0
